#!/usr/bin/env node

var argvs = process.argv
console.log(argvs)


if(argvs[2] ==('stop')){
console.log ("stop")
	require('forever').stopAll('lib/NAMadapter.js') 
} else {
	if(argvs[2] == ('-d' || '--daemon')){
	console.log ("daemon")
		require('forever').startDaemon(process.cwd() +'/lib/NAMadapter.js', {logFile : '/var/log/nam_adapter.log' }) 
	} else {
		require('forever').start(process.cwd() + '/lib/NAMadapter.js', {logFile : '/var/log/nam_adapter.log' }) 
	}
}

